# Site settings
title: E. K. Batey III ("Trey")
email: tbatey@lowercolumbia.edu
description: > # this means to ignore newlines until "baseurl:"
  A website for my professional academic and research activities, as well as personal musings and rants.
baseurl: "/research" # the subpath of your site, e.g. /blog/
url: "http://tbatey.org" # the base hostname & protocol for your site
twitter_username: bateytk
github_username:  bateyt

# Build settings
markdown: kramdown

# Encoding
encoding: utf-8

# Other options
permalink: blog/:year/:month/:title
job.title: "Instructor---Social Sciences"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""